# Generated by Django 5.1.2 on 2024-10-14 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='estado',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('En progreso', 'En progreso'), ('En revisión', 'En revisión'), ('Completado', 'Completado')], default='Iniciado', max_length=20),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo',
            field=models.CharField(choices=[('desarrollo-web', 'Desarrollo Web'), ('diseno-grafico', 'Diseño Gráfico'), ('gestion-producto', 'Gestión de Producto'), ('marketing', 'Marketing')], max_length=100),
        ),
    ]
