# Generated by Django 5.1.2 on 2024-10-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_proyectos_estado_proyectos_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='fecha_inicio',
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='estado',
            field=models.CharField(default='Planeando', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
