# Generated by Django 5.1.2 on 2024-10-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_admin_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cliente'),
        ),
    ]
