# Generated by Django 5.1.2 on 2024-10-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_proyectos_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Completada', 'Completada'), ('En progreso', 'En progreso'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
            ],
        ),
    ]
