# Generated by Django 5.1.2 on 2024-10-31 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_admin_user_user_block_remove_documento_proyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_user',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='fecha_registro',
        ),
    ]
