# Generated by Django 5.1.2 on 2024-10-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_admin_user_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
